services:
  auth:
    build:
      context: ./auth
    volumes:
      - ./auth/auth.py:/app/auth.py
  traefik:
    image: traefik:v3.2
    volumes:
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml
      - ./traefik/routes.yml:/etc/traefik/routes.yml
    ports:
      - "8080:80"
      - "8081:8080"  # Traefik dashboard
    depends_on:
      - auth